while True:
    a = input()
    b = a.replace("1.", "a")
    b = b.replace("2.", "b")
    b = b.replace("3.", "c")
    b = b.replace("4.", "d")
    b = b.replace("5.", "e")
    b = b.replace("6.", "f")
    b = b.replace("7.", "g")
    b = b.replace("8.", "h")
    b = b.replace("9.", "i")
    b = b.replace("!.", "j")
    b = b.replace("@.", "k")
    b = b.replace("#.", "l")
    b = b.replace("$.", "m")
    b = b.replace("%.", "n")
    b = b.replace("^.", "o")
    b = b.replace("&.", "p")
    b = b.replace("*.", "q")
    b = b.replace("(.", "r")
    b = b.replace(").", "s")
    b = b.replace("_.", "t")
    b = b.replace("-.", "u")
    b = b.replace("+.", "v")
    b = b.replace("=.", "w")
    b = b.replace("[.", "x")
    b = b.replace("].", "y")
    b = b.replace("{.", "z")
    b = b.replace("/", " ")
    print(b)