while True:
    a = input()
    b = a.lower()
    b = b.replace("a", "1.")
    b = b.replace("b", "2.")
    b = b.replace("c", "3.")
    b = b.replace("d", "4.")
    b = b.replace("e", "5.")
    b = b.replace("f", "6.")
    b = b.replace("g", "7.")
    b = b.replace("h", "8.")
    b = b.replace("i", "9.")
    b = b.replace("j", "!.")
    b = b.replace("k", "@.")
    b = b.replace("l", "#.")
    b = b.replace("m", "$.")
    b = b.replace("n", "%.")
    b = b.replace("o", "^.")
    b = b.replace("p", "&.")
    b = b.replace("q", "*.")
    b = b.replace("r", "(.")
    b = b.replace("s", ").")
    b = b.replace("t", "_.")
    b = b.replace("u", "-.")
    b = b.replace("v", "+.")
    b = b.replace("w", "=.")
    b = b.replace("x", "[.")
    b = b.replace("y", "].")
    b = b.replace("z", "{.")
    b = b.replace(" ", "/")
    print(b)